In [75]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [76]:
#2. Print the NUMPY version and the configuration.
print("NUMPY version:", np.__version__)

NUMPY version: 1.24.3


In [77]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

#4. Print a.

#First way:
a = np.random.random((2, 3, 5))
print("\nRandom a:")
print(a)


Random a:
[[[0.01804724 0.84121271 0.89656835 0.20836297 0.28470849]
  [0.37637671 0.61588687 0.50231167 0.23914091 0.98076424]
  [0.83983762 0.9965009  0.93058527 0.23585349 0.13215324]]

 [[0.55089943 0.78525117 0.66779834 0.91716497 0.38695266]
  [0.01975025 0.1755606  0.48700359 0.40173949 0.74219861]
  [0.6546975  0.65545621 0.0551612  0.20498119 0.03036943]]]


In [78]:
#Second way
a = np.random.rand(2, 3, 5)
print("\nRandom a:")
print(a)


Random a:
[[[0.02600769 0.33485055 0.50852687 0.67186166 0.10360211]
  [0.85130164 0.94471426 0.72178132 0.89309295 0.77408992]
  [0.25259884 0.86757981 0.58685482 0.08916355 0.92957905]]

 [[0.76754321 0.29447067 0.64291765 0.92238358 0.2315638 ]
  [0.14367337 0.45449659 0.53360715 0.14992806 0.81528098]
  [0.68686787 0.88013715 0.82640743 0.94234739 0.14712156]]]


In [79]:
#Third way
a = np.random.random_sample((2, 3, 5))
print("\nRandom a:")
print(a)


Random a:
[[[0.45982532 0.1615883  0.82190675 0.48592214 0.57861784]
  [0.7680694  0.05550224 0.71747713 0.25776932 0.0817923 ]
  [0.66352261 0.68237208 0.44874052 0.79626171 0.176852  ]]

 [[0.3360206  0.18778181 0.41869553 0.70084408 0.81571604]
  [0.00620504 0.19671088 0.36047831 0.31422505 0.45079307]
  [0.78770108 0.34619989 0.57782769 0.51887395 0.47961071]]]


In [80]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5, 2, 3))

#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [86]:
#7. Do a and b have the same size? How do you prove that in Python code?

a = np.random.random((2, 3, 5))
b = np.ones((5,2,3))

if a==b:
    print("'a' y 'b' tienen el mismo tamaño.")
else:
    print("'a' y 'b' no tienen el mismo tamaño.")

'a' y 'b' no tienen el mismo tamaño.


/var/folders/zr/v_qv79zn4xv2dhqwl7djvy340000gn/T/ipykernel_20072/1335465900.py:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if a==b:


In [112]:
are_equal = np.array_equal(a, b)

# Print the result
if are_equal:
    print("Matrix e is equal to matrix a.")
else:
    print("Matrix e is not equal to matrix a.")

Matrix e is not equal to matrix a.


In [87]:
#8. Are you able to add a and b? Why or why not?

c = a+b
print (c) 
#Esta operación nos dará error porque las dos matrices tienen dimensiones diferentes.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [84]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b, (1, 2, 0))

#Transponemos la matriz b
print("\nTransposed b (c):")
print(c)


Transposed b (c):
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [90]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

#Vamos a sumar a y c
d = a + c
print("\nMatriz d:")
print(d)
# El motivo por el que ahora podemos sumar las dos variables es porque las dos matrices tienen las mismas dimensiones


Random d:
[[[1.00445395 1.21942737 1.41832949 1.44473673 1.22806883]
  [1.46058188 1.70576369 1.37167849 1.73586312 1.5111411 ]
  [1.2786261  1.78661907 1.47196147 1.22112938 1.77133352]]

 [[1.24810382 1.21392517 1.56445085 1.7749839  1.48495272]
  [1.93756653 1.83831751 1.44459652 1.85032421 1.52761249]
  [1.80268251 1.61472088 1.85573922 1.36238148 1.50365057]]]


In [96]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print("\nLa matriz 'a' es:")
print(a)
print("\nLa matriz 'd' es:")
print(d)

#La diferencia en termino de valores es que la matriz 'a' tiene sus valores entre 0 y 1 y la matriz 'b' tiene sus valores entre 1 y 2. 
#La realación entre ellas es que tienen usan valores float.


La matriz 'a' es:
[[[0.00445395 0.21942737 0.41832949 0.44473673 0.22806883]
  [0.46058188 0.70576369 0.37167849 0.73586312 0.5111411 ]
  [0.2786261  0.78661907 0.47196147 0.22112938 0.77133352]]

 [[0.24810382 0.21392517 0.56445085 0.7749839  0.48495272]
  [0.93756653 0.83831751 0.44459652 0.85032421 0.52761249]
  [0.80268251 0.61472088 0.85573922 0.36238148 0.50365057]]]

La matriz 'd' es:
[[[1.00445395 1.21942737 1.41832949 1.44473673 1.22806883]
  [1.46058188 1.70576369 1.37167849 1.73586312 1.5111411 ]
  [1.2786261  1.78661907 1.47196147 1.22112938 1.77133352]]

 [[1.24810382 1.21392517 1.56445085 1.7749839  1.48495272]
  [1.93756653 1.83831751 1.44459652 1.85032421 1.52761249]
  [1.80268251 1.61472088 1.85573922 1.36238148 1.50365057]]]


In [105]:
#12. Multiply a and c. Assign the result to e.
#Vamos a multiplicar 'a' y 'c' y guardarlo en una variable llamada 'e'.
e = a * c
print("\nMatriz e:")
print(e)


Matriz e:
[[[0.00445395 0.21942737 0.41832949 0.44473673 0.22806883]
  [0.46058188 0.70576369 0.37167849 0.73586312 0.5111411 ]
  [0.2786261  0.78661907 0.47196147 0.22112938 0.77133352]]

 [[0.24810382 0.21392517 0.56445085 0.7749839  0.48495272]
  [0.93756653 0.83831751 0.44459652 0.85032421 0.52761249]
  [0.80268251 0.61472088 0.85573922 0.36238148 0.50365057]]]


In [113]:
#13. Does e equal to a? Why or why not?
son_iguales = np.array_equal(a, e)

if son_iguales:
    print("La matriz 'e' no es igual a la matriz 'a'")
else:
    print("La matriz e es igual a la matriz 'e'")
    
#Las matrices no son iguales ya que los valores difieren de unas a otras, todo y tener las mismas dimensiones.

La matriz 'e' no es igual a la matriz 'a'


In [122]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

#Valor máximo en d:
d_max = np.max(d)
print("valor máximo de la matriz 'd':" ,d_max)

#Valor mínimo en d:
d_min = np.min(d)
print("valor mínimo de la matriz 'd':" ,d_min)

#Valor medio en d:
d_mean = np.mean(d)
print("valor medio de la matriz 'd':" ,d_mean) 

valor máximo de la matriz 'd': 1.9375665302567673
valor mínimo de la matriz 'd': 1.0044539528768102
valor medio de la matriz 'd': 1.5217907524732928


In [123]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

#Vamos a crear un matriz vacia.
f=np.empty((2, 3, 5))
print(f)

[[[0.00445395 0.21942737 0.41832949 0.44473673 0.22806883]
  [0.46058188 0.70576369 0.37167849 0.73586312 0.5111411 ]
  [0.2786261  0.78661907 0.47196147 0.22112938 0.77133352]]

 [[0.24810382 0.21392517 0.56445085 0.7749839  0.48495272]
  [0.93756653 0.83831751 0.44459652 0.85032421 0.52761249]
  [0.80268251 0.61472088 0.85573922 0.36238148 0.50365057]]]


In [131]:
#16.Populate the values in f. 
"""
For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

f=np.empty((2, 3, 5))

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i][j][k] = 25
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i][j][k] = 75
            elif d[i, j, k] == d_mean:
                f[i][j][k] = 50
            elif d[i, j, k] == d_min:
                f[i][j][k] = 0
            elif d[i, j, k] == d_max:
                f[i][j][k] = 100

In [138]:

#17. Print d and f. Do you have your expected f?
"""For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

                
print("\nPopulated array f:")
print(f)
#El resultado es el esperado


Populated array f:
[[[  0.  25.  25.  25.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  75.  25.  25.  75.]]

 [[ 25.  25.  75.  75.  25.]
  [100.  75.  25.  75.  75.]
  [ 75.  75.  75.  25.  25.]]]


In [149]:

#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values ("A", "B", "C", "D", and "E") to label the array elements?
"""
 You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
f=np.empty((2, 3, 5), dtype=str)
#Vamos a crear un diccionario para hacer una key value, asignar a cada valor un letra.

etiqueta = {0: "A",25: "B",50: "C",75: "D",100: "E"}

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i][j][k] = etiqueta[25]
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i][j][k] = etiqueta[75]
            elif d[i, j, k] == d_mean:
                f[i][j][k] = etiqueta[50]
            elif d[i, j, k] == d_min:
                f[i][j][k] = etiqueta[0]
            elif d[i, j, k] == d_max:
                f[i][j][k] = etiqueta[100]
print(f)

[[['A' 'B' 'B' 'B' 'B']
  ['B' 'D' 'B' 'D' 'B']
  ['B' 'D' 'B' 'B' 'D']]

 [['B' 'B' 'D' 'D' 'B']
  ['E' 'D' 'B' 'D' 'D']
  ['D' 'D' 'D' 'B' 'B']]]
